# Generated by Django 5.0.1 on 2024-01-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog3', '0004_comment_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
