# Generated by Django 5.0.1 on 2024-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog3', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
