# Generated by Django 5.0.1 on 2024-05-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog3', '0007_myblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='your_comment',
        ),
    ]
