# Generated by Django 5.0.1 on 2024-05-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog3', '0008_rename_content_comment_your_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='your_comment',
            new_name='content',
        ),
    ]
